# Generated by Django 5.2.8 on 2025-11-29 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATEMControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('type', models.CharField(choices=[('connection', 'Connection'), ('disconnection', 'Disconnection')], db_index=True, max_length=20, verbose_name='Type')),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atem_control_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATEM Control Log',
                'verbose_name_plural': 'ATEM Control Logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='atem_contro_user_id_3d6bb9_idx'), models.Index(fields=['user', 'type', '-date'], name='atem_contro_user_id_4c1ee4_idx')],
            },
        ),
    ]
