# Generated by Django 6.0.7 on 2026-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atem_control', '0002_switcher'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='atemcontrollog',
            name='atem_contro_user_id_3d6bb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='atemcontrollog',
            name='atem_contro_user_id_4c1ee4_idx',
        ),
        migrations.AddIndex(
            model_name='atemcontrollog',
            index=models.Index(fields=['type', '-date'], name='atem_contro_type_56f6ca_idx'),
        ),
        migrations.RemoveField(
            model_name='atemcontrollog',
            name='user',
        ),
    ]
