# Generated by Django 6.0.7 on 2026-08-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atem_control', '0003_remove_atemcontrollog_atem_contro_user_id_3d6bb9_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Switcher',
        ),
    ]
