name: mactest
on:
  workflow_dispatch: {}
jobs:
  intel:
    runs-on: macos-13
    timeout-minutes: 5
    steps:
      - run: sw_vers; uname -m
  arm:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - run: sw_vers; uname -m
